### ISSUE TITLE
Registrera en applikation som API nyckel binds till.

### ISSUE THREAD

**Issue by mc22ft** [ChristofferGoude/1DV450_cg222gb#11]
Jag saknar att man som inloggad kan registrera en applikation och därmed bli tilldelad en API nyckel till applikationen som blir registrerad. Det underlättar när admin eller användaren ska radera en nyckel som tillhör en viss applikation.

**Comment by 1dv450** [comment]
Gå igenom denna och den andra issuen och fixa/stäng den när du anser den vara klar.

**Comment by ChristofferGoude** [comment]
Fixat så man kan registrera en applikation, samt städat upp routings och vyer mellan administratören och vanliga användare. Applikationen är nu mer logiskt utformad rent kodmässigt.
