### ISSUE TITLE
Felmeddelenade vid duplicerad epost

### ISSUE THREAD

**Issue by 1dv450** [ChristofferGoude/1DV450_cg222gb#4]
När man försöker skapa en ny användare med en epost som redan finns får man ett lite otydligt felmeddelande. Sånt kan förvirra användare och göra att de inte använder tjänsten. Bör vara ett mer informativt felmeddelande

**Comment by ChristofferGoude** [comment]
Har städat upp felmeddelanden vid registrering, det finns fortfarande lite att göra för att förtydliga för användaren men nu är det åtminstonde lite tydligare.
