### ISSUE TITLE
...en registrerad applikationsutvecklare att kunna se / ta bort sin nykel.

### ISSUE THREAD

**Issue by 1dv450** [ChristofferGoude/1DV450_cg222gb#5]
Hur kan en inloggad användare tabort/regenerera sin nyckel? Skulle man ju vilja ifall den hamnat på villovägar (någon annan ha rnorpat den).

**Comment by ChristofferGoude** [comment]
Lagt till funktionalitet så användaren själv kan ta bort sin nyckel (och sedan be om en ny) om det behövs.
